import Foundation

/// Type of a schema object.
public enum SchemaObjectKind: String, Sendable {
    case table, view, materializedView
}

/// A basic representation of a schema object.
public struct SchemaObject: Sendable {
    public var schema: String
    public var name: String
    public var kind: SchemaObjectKind

    public init(schema: String, name: String, kind: SchemaObjectKind) {
        self.schema = schema
        self.name = name
        self.kind = kind
    }
}

/// Column information.
public struct PostgresColumnInfo: Sendable {
    public let name: String
    public let dataType: String
    public let isNullable: Bool
    public let defaultValue: String?
    /// Whether the column is an identity column (`GENERATED ALWAYS` or `GENERATED BY DEFAULT`).
    public let isIdentity: Bool
    /// `"ALWAYS"` or `"BY DEFAULT"` for identity columns, `nil` otherwise.
    public let identityGeneration: String?
    /// The collation name for this column, `nil` if using the default collation.
    public let collation: String?

    public init(name: String, dataType: String, isNullable: Bool, defaultValue: String?, isIdentity: Bool = false, identityGeneration: String? = nil, collation: String? = nil) {
        self.name = name
        self.dataType = dataType
        self.isNullable = isNullable
        self.defaultValue = defaultValue
        self.isIdentity = isIdentity
        self.identityGeneration = identityGeneration
        self.collation = collation
    }
}

/// Detailed column information including constraints.
public struct PostgresColumnDetail: Sendable {
    public struct ForeignKeyRef: Sendable {
        public let constraintName: String
        public let referencedSchema: String
        public let referencedTable: String
        public let referencedColumn: String

        public init(constraintName: String, referencedSchema: String, referencedTable: String, referencedColumn: String) {
            self.constraintName = constraintName
            self.referencedSchema = referencedSchema
            self.referencedTable = referencedTable
            self.referencedColumn = referencedColumn
        }
    }
    public let name: String
    public let dataType: String
    public let isNullable: Bool
    public let maxLength: Int?
    public let isPrimaryKey: Bool
    public let foreignKey: ForeignKeyRef?

    public init(name: String, dataType: String, isNullable: Bool, maxLength: Int?, isPrimaryKey: Bool, foreignKey: ForeignKeyRef?) {
        self.name = name
        self.dataType = dataType
        self.isNullable = isNullable
        self.maxLength = maxLength
        self.isPrimaryKey = isPrimaryKey
        self.foreignKey = foreignKey
    }
}

/// Index information.
public struct PostgresIndexInfo: Sendable {
    public struct Column: Sendable {
        public let name: String
        public let isDescending: Bool
        /// Whether this is an INCLUDE (non-key) column rather than a key column.
        public let isIncluded: Bool

        public init(name: String, isDescending: Bool, isIncluded: Bool = false) {
            self.name = name
            self.isDescending = isDescending
            self.isIncluded = isIncluded
        }
    }
    public let name: String
    public let isUnique: Bool
    public let columns: [Column]
    public let predicate: String?
    /// The index access method (e.g., `"btree"`, `"hash"`, `"gin"`, `"gist"`, `"brin"`).
    public let indexType: String?

    public init(name: String, isUnique: Bool, columns: [Column], predicate: String?, indexType: String? = nil) {
        self.name = name
        self.isUnique = isUnique
        self.columns = columns
        self.predicate = predicate
        self.indexType = indexType
    }
}

/// Primary key information.
public struct PostgresPrimaryKeyInfo: Sendable {
    public let name: String
    public let columns: [String]
    public let isDeferrable: Bool
    public let isInitiallyDeferred: Bool

    public init(name: String, columns: [String], isDeferrable: Bool = false, isInitiallyDeferred: Bool = false) {
        self.name = name
        self.columns = columns
        self.isDeferrable = isDeferrable
        self.isInitiallyDeferred = isInitiallyDeferred
    }
}

/// Foreign key information.
public struct PostgresForeignKeyInfo: Sendable {
    public let name: String
    public let columns: [String]
    public let referencedSchema: String
    public let referencedTable: String
    public let referencedColumns: [String]
    public let onUpdate: String?
    public let onDelete: String?
    public let isDeferrable: Bool
    public let isInitiallyDeferred: Bool

    public init(name: String, columns: [String], referencedSchema: String, referencedTable: String, referencedColumns: [String], onUpdate: String?, onDelete: String?, isDeferrable: Bool = false, isInitiallyDeferred: Bool = false) {
        self.name = name
        self.columns = columns
        self.referencedSchema = referencedSchema
        self.referencedTable = referencedTable
        self.referencedColumns = referencedColumns
        self.onUpdate = onUpdate
        self.onDelete = onDelete
        self.isDeferrable = isDeferrable
        self.isInitiallyDeferred = isInitiallyDeferred
    }
}

/// Unique constraint information.
public struct PostgresUniqueConstraintInfo: Sendable {
    public let name: String
    public let columns: [String]
    public let isDeferrable: Bool
    public let isInitiallyDeferred: Bool

    public init(name: String, columns: [String], isDeferrable: Bool = false, isInitiallyDeferred: Bool = false) {
        self.name = name
        self.columns = columns
        self.isDeferrable = isDeferrable
        self.isInitiallyDeferred = isInitiallyDeferred
    }
}

/// Check constraint information.
public struct PostgresCheckConstraintInfo: Sendable {
    public let name: String
    public let expression: String

    public init(name: String, expression: String) {
        self.name = name
        self.expression = expression
    }
}

/// Dependency information between objects.
public struct PostgresDependencyInfo: Sendable {
    public let name: String
    public let sourceTable: String
    public let referencingColumns: [String]
    public let referencedColumns: [String]
    public let onUpdate: String?
    public let onDelete: String?

    public init(name: String, sourceTable: String, referencingColumns: [String], referencedColumns: [String], onUpdate: String?, onDelete: String?) {
        self.name = name
        self.sourceTable = sourceTable
        self.referencingColumns = referencingColumns
        self.referencedColumns = referencedColumns
        self.onUpdate = onUpdate
        self.onDelete = onDelete
    }
}

/// Extension information.
public struct PostgresExtensionInfo: Sendable {
    public let name: String
    public let schema: String
    public let version: String
    public let relocatable: Bool

    public init(name: String, schema: String, version: String, relocatable: Bool) {
        self.name = name
        self.schema = schema
        self.version = version
        self.relocatable = relocatable
    }
}

/// Table-level storage and configuration properties.
public struct PostgresTableProperties: Sendable {
    public let fillfactor: Int?
    public let toastTupleTarget: Int?
    public let autovacuumEnabled: Bool?
    public let parallelWorkers: Int?
    public let tablespace: String?

    public init(fillfactor: Int? = nil, toastTupleTarget: Int? = nil, autovacuumEnabled: Bool? = nil, parallelWorkers: Int? = nil, tablespace: String? = nil) {
        self.fillfactor = fillfactor
        self.toastTupleTarget = toastTupleTarget
        self.autovacuumEnabled = autovacuumEnabled
        self.parallelWorkers = parallelWorkers
        self.tablespace = tablespace
    }
}

/// Information about an object owned by an extension.
public struct PostgresExtensionObject: Sendable {
    public let schema: String
    public let name: String
    public let type: String

    public init(schema: String, name: String, type: String) {
        self.schema = schema
        self.name = name
        self.type = type
    }
}

/// Available extension information.
public struct PostgresAvailableExtensionInfo: Sendable {
    public let name: String
    public let defaultVersion: String
    public let installedVersion: String?
    public let comment: String?

    public init(name: String, defaultVersion: String, installedVersion: String?, comment: String?) {
        self.name = name
        self.defaultVersion = defaultVersion
        self.installedVersion = installedVersion
        self.comment = comment
    }
}

/// Column comment information.
public struct PostgresColumnComment: Sendable {
    public let column: String
    public let comment: String?

    public init(column: String, comment: String?) {
        self.column = column
        self.comment = comment
    }
}
