import Foundation

/// Type of a schema object.
public enum SchemaObjectKind: String, Sendable {
    case table, view, materializedView
}

/// A basic representation of a schema object.
public struct SchemaObject: Sendable {
    public var schema: String
    public var name: String
    public var kind: SchemaObjectKind

    public init(schema: String, name: String, kind: SchemaObjectKind) {
        self.schema = schema
        self.name = name
        self.kind = kind
    }
}

/// Column information.
public struct PostgresColumnInfo: Sendable {
    public let name: String
    public let dataType: String
    public let isNullable: Bool
    public let defaultValue: String?
    /// Whether the column is an identity column (`GENERATED ALWAYS` or `GENERATED BY DEFAULT`).
    public let isIdentity: Bool
    /// `"ALWAYS"` or `"BY DEFAULT"` for identity columns, `nil` otherwise.
    public let identityGeneration: String?
    /// The collation name for this column, `nil` if using the default collation.
    public let collation: String?

    public init(name: String, dataType: String, isNullable: Bool, defaultValue: String?, isIdentity: Bool = false, identityGeneration: String? = nil, collation: String? = nil) {
        self.name = name
        self.dataType = dataType
        self.isNullable = isNullable
        self.defaultValue = defaultValue
        self.isIdentity = isIdentity
        self.identityGeneration = identityGeneration
        self.collation = collation
    }
}

/// Detailed column information including constraints.
public struct PostgresColumnDetail: Sendable {
    public struct ForeignKeyRef: Sendable {
        public let constraintName: String
        public let referencedSchema: String
        public let referencedTable: String
        public let referencedColumn: String

        public init(constraintName: String, referencedSchema: String, referencedTable: String, referencedColumn: String) {
            self.constraintName = constraintName
            self.referencedSchema = referencedSchema
            self.referencedTable = referencedTable
            self.referencedColumn = referencedColumn
        }
    }
    public let name: String
    public let dataType: String
    public let isNullable: Bool
    public let maxLength: Int?
    public let isPrimaryKey: Bool
    public let foreignKey: ForeignKeyRef?

    public init(name: String, dataType: String, isNullable: Bool, maxLength: Int?, isPrimaryKey: Bool, foreignKey: ForeignKeyRef?) {
        self.name = name
        self.dataType = dataType
        self.isNullable = isNullable
        self.maxLength = maxLength
        self.isPrimaryKey = isPrimaryKey
        self.foreignKey = foreignKey
    }
}

/// Index information.
public struct PostgresIndexInfo: Sendable {
    public struct Column: Sendable {
        public let name: String
        public let isDescending: Bool
        /// Whether this is an INCLUDE (non-key) column rather than a key column.
        public let isIncluded: Bool

        public init(name: String, isDescending: Bool, isIncluded: Bool = false) {
            self.name = name
            self.isDescending = isDescending
            self.isIncluded = isIncluded
        }
    }
    public let name: String
    public let isUnique: Bool
    public let columns: [Column]
    public let predicate: String?
    /// The index access method (e.g., `"btree"`, `"hash"`, `"gin"`, `"gist"`, `"brin"`).
    public let indexType: String?

    public init(name: String, isUnique: Bool, columns: [Column], predicate: String?, indexType: String? = nil) {
        self.name = name
        self.isUnique = isUnique
        self.columns = columns
        self.predicate = predicate
        self.indexType = indexType
    }
}

/// Primary key information.
public struct PostgresPrimaryKeyInfo: Sendable {
    public let name: String
    public let columns: [String]
    public let isDeferrable: Bool
    public let isInitiallyDeferred: Bool

    public init(name: String, columns: [String], isDeferrable: Bool = false, isInitiallyDeferred: Bool = false) {
        self.name = name
        self.columns = columns
        self.isDeferrable = isDeferrable
        self.isInitiallyDeferred = isInitiallyDeferred
    }
}

/// Foreign key information.
public struct PostgresForeignKeyInfo: Sendable {
    public let name: String
    public let columns: [String]
    public let referencedSchema: String
    public let referencedTable: String
    public let referencedColumns: [String]
    public let onUpdate: String?
    public let onDelete: String?
    public let isDeferrable: Bool
    public let isInitiallyDeferred: Bool

    public init(name: String, columns: [String], referencedSchema: String, referencedTable: String, referencedColumns: [String], onUpdate: String?, onDelete: String?, isDeferrable: Bool = false, isInitiallyDeferred: Bool = false) {
        self.name = name
        self.columns = columns
        self.referencedSchema = referencedSchema
        self.referencedTable = referencedTable
        self.referencedColumns = referencedColumns
        self.onUpdate = onUpdate
        self.onDelete = onDelete
        self.isDeferrable = isDeferrable
        self.isInitiallyDeferred = isInitiallyDeferred
    }
}

/// Unique constraint information.
public struct PostgresUniqueConstraintInfo: Sendable {
    public let name: String
    public let columns: [String]
    public let isDeferrable: Bool
    public let isInitiallyDeferred: Bool

    public init(name: String, columns: [String], isDeferrable: Bool = false, isInitiallyDeferred: Bool = false) {
        self.name = name
        self.columns = columns
        self.isDeferrable = isDeferrable
        self.isInitiallyDeferred = isInitiallyDeferred
    }
}

/// Check constraint information.
public struct PostgresCheckConstraintInfo: Sendable {
    public let name: String
    public let expression: String

    public init(name: String, expression: String) {
        self.name = name
        self.expression = expression
    }
}

/// Dependency information between objects.
public struct PostgresDependencyInfo: Sendable {
    public let name: String
    public let sourceTable: String
    public let referencingColumns: [String]
    public let referencedColumns: [String]
    public let onUpdate: String?
    public let onDelete: String?

    public init(name: String, sourceTable: String, referencingColumns: [String], referencedColumns: [String], onUpdate: String?, onDelete: String?) {
        self.name = name
        self.sourceTable = sourceTable
        self.referencingColumns = referencingColumns
        self.referencedColumns = referencedColumns
        self.onUpdate = onUpdate
        self.onDelete = onDelete
    }
}

/// Extension information.
public struct PostgresExtensionInfo: Sendable {
    public let name: String
    public let schema: String
    public let version: String
    public let relocatable: Bool

    public init(name: String, schema: String, version: String, relocatable: Bool) {
        self.name = name
        self.schema = schema
        self.version = version
        self.relocatable = relocatable
    }
}

/// Table-level storage and configuration properties.
public struct PostgresTableProperties: Sendable {
    public let fillfactor: Int?
    public let toastTupleTarget: Int?
    public let autovacuumEnabled: Bool?
    public let parallelWorkers: Int?
    public let tablespace: String?

    public init(fillfactor: Int? = nil, toastTupleTarget: Int? = nil, autovacuumEnabled: Bool? = nil, parallelWorkers: Int? = nil, tablespace: String? = nil) {
        self.fillfactor = fillfactor
        self.toastTupleTarget = toastTupleTarget
        self.autovacuumEnabled = autovacuumEnabled
        self.parallelWorkers = parallelWorkers
        self.tablespace = tablespace
    }
}

/// Information about an object owned by an extension.
public struct PostgresExtensionObject: Sendable {
    public let schema: String
    public let name: String
    public let type: String

    public init(schema: String, name: String, type: String) {
        self.schema = schema
        self.name = name
        self.type = type
    }
}

/// Available extension information.
public struct PostgresAvailableExtensionInfo: Sendable {
    public let name: String
    public let defaultVersion: String
    public let installedVersion: String?
    public let comment: String?

    public init(name: String, defaultVersion: String, installedVersion: String?, comment: String?) {
        self.name = name
        self.defaultVersion = defaultVersion
        self.installedVersion = installedVersion
        self.comment = comment
    }
}

/// Comprehensive table details including storage parameters, owner, tablespace, etc.
public struct PostgresTableDetails: Sendable {
    public let oid: Int
    public let name: String
    public let schema: String
    public let owner: String
    public let tablespace: String?
    public let hasIndexes: Bool
    public let hasRules: Bool
    public let hasTriggers: Bool
    public let rowSecurity: Bool
    public let forceRowSecurity: Bool
    public let isPartitioned: Bool
    public let description: String?
    public let acl: String?
    /// Storage options (reloptions) like fillfactor=90.
    public let options: [String]?
    public let estimatedRowCount: Int
    public let totalSizeBytes: Int64
    public let tableSizeBytes: Int64
    public let indexesSizeBytes: Int64

    public init(
        oid: Int, name: String, schema: String, owner: String, tablespace: String?,
        hasIndexes: Bool, hasRules: Bool, hasTriggers: Bool,
        rowSecurity: Bool, forceRowSecurity: Bool, isPartitioned: Bool,
        description: String?, acl: String?, options: [String]?,
        estimatedRowCount: Int, totalSizeBytes: Int64, tableSizeBytes: Int64, indexesSizeBytes: Int64
    ) {
        self.oid = oid
        self.name = name
        self.schema = schema
        self.owner = owner
        self.tablespace = tablespace
        self.hasIndexes = hasIndexes
        self.hasRules = hasRules
        self.hasTriggers = hasTriggers
        self.rowSecurity = rowSecurity
        self.forceRowSecurity = forceRowSecurity
        self.isPartitioned = isPartitioned
        self.description = description
        self.acl = acl
        self.options = options
        self.estimatedRowCount = estimatedRowCount
        self.totalSizeBytes = totalSizeBytes
        self.tableSizeBytes = tableSizeBytes
        self.indexesSizeBytes = indexesSizeBytes
    }
}

/// Detailed column information including defaults, identity, generated, comments.
public struct PostgresColumnDetails: Sendable {
    public let name: String
    public let dataType: String
    public let ordinalPosition: Int
    public let isNullable: Bool
    public let defaultValue: String?
    public let isIdentity: Bool
    public let identityGeneration: String?
    public let isGenerated: Bool
    public let generationExpression: String?
    public let collation: String?
    public let statisticsTarget: Int?
    public let storage: String?
    public let description: String?
    public let maxLength: Int?

    public init(
        name: String, dataType: String, ordinalPosition: Int, isNullable: Bool,
        defaultValue: String?, isIdentity: Bool, identityGeneration: String?,
        isGenerated: Bool, generationExpression: String?, collation: String?,
        statisticsTarget: Int?, storage: String?, description: String?, maxLength: Int?
    ) {
        self.name = name
        self.dataType = dataType
        self.ordinalPosition = ordinalPosition
        self.isNullable = isNullable
        self.defaultValue = defaultValue
        self.isIdentity = isIdentity
        self.identityGeneration = identityGeneration
        self.isGenerated = isGenerated
        self.generationExpression = generationExpression
        self.collation = collation
        self.statisticsTarget = statisticsTarget
        self.storage = storage
        self.description = description
        self.maxLength = maxLength
    }
}

/// Row-level security status for a table.
public struct PostgresRLSStatus: Sendable {
    public let rowSecurity: Bool
    public let forceRowSecurity: Bool

    public init(rowSecurity: Bool, forceRowSecurity: Bool) {
        self.rowSecurity = rowSecurity
        self.forceRowSecurity = forceRowSecurity
    }
}

/// Trigger information for a table.
public struct PostgresTriggerInfo: Sendable {
    public let name: String
    /// Full event description (e.g. "BEFORE INSERT").
    public let event: String
    /// The DML manipulation: INSERT, UPDATE, DELETE.
    public let manipulation: String
    /// ROW or STATEMENT.
    public let orientation: String
    /// BEFORE, AFTER, or INSTEAD OF.
    public let timing: String
    /// The function invoked by the trigger.
    public let functionName: String
    public let isEnabled: Bool
    /// The full trigger definition SQL.
    public let definition: String?

    public init(
        name: String, event: String, manipulation: String, orientation: String,
        timing: String, functionName: String, isEnabled: Bool, definition: String?
    ) {
        self.name = name
        self.event = event
        self.manipulation = manipulation
        self.orientation = orientation
        self.timing = timing
        self.functionName = functionName
        self.isEnabled = isEnabled
        self.definition = definition
    }
}

/// Sequence information.
public struct PostgresSequenceInfo: Sendable {
    public let name: String
    public let schema: String

    public init(name: String, schema: String) {
        self.name = name
        self.schema = schema
    }
}

/// User-defined type information.
public struct PostgresTypeInfo: Sendable {
    public let name: String
    public let schema: String
    /// The kind of user-defined type: `"enum"`, `"composite"`, `"range"`, or `"domain"`.
    public let kind: String

    public init(name: String, schema: String, kind: String) {
        self.name = name
        self.schema = schema
        self.kind = kind
    }
}

/// Column comment information.
public struct PostgresColumnComment: Sendable {
    public let column: String
    public let comment: String?

    public init(column: String, comment: String?) {
        self.column = column
        self.comment = comment
    }
}
